version: '3.3'

services:
  scope:
    image: weaveworks/scope:1.6.3
    privileged: true
    labels:
      - "works.weave.role=system"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker=true"

  ui:
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: ./entrypoint.sh
    ports: 
      - '4042:4042'
    depends_on:
      - 'scope'
