/* START :: NOTIFICATION CONFIG VARIABLES */
export const NOTIFICATION_POLLING_DURATION = 5;
export const IS_NOTIFICATION_CHECK_ENABLE = true;
/* END :: NOTIFICATION CONFIG VARIABLES */

/* START :: VISUALIZATION CONFIG VARIABLES */
export const CVE_BUBBLE_CHART_UPPER_BOUND_LIMIT = 750;
export const RESOURCE_BUBBLE_CHART_UPPER_BOUND_LIMIT = 300;
export const BUBBLE_DEFAULT_RADIUS = 1;
export const BUBBLE_CHART_UPPER_BOUND_LIMIT_MESSAGE = {
  error: {
    message: 'Too much data to visualize, please use search queries to filter appropriately.'
  }
};
/* END :: VISUALIZATION CONFIG VARIABLES */
